### ISSUE TITLE
reversing the beta coefficients

### ISSUE THREAD

**Issue by santarabantoosoo** [petersonR/bestNormalize#1]
Firstly, thank you so much for the package..

Secondly, I can understand that inverse = True can reverse the transformation. However, if I transformed the outcome variable and then fitted a linear regression model, how can I interpret the beta coefficients produced by the model, or how can I re-transform it back ?

**Comment by petersonR** [comment]
Interpreting the beta coefficients post-transformation can be tough. It will depend on the specific transformation that you used. If you are using a simple log transformation it's a matter of exponentiating the coefficients, but if you are using an ORQ transformation it's practically impossible to interpret the beta effects. 

This is because the transformation function itself will look completely different for different distributions. Furthermore, when you use the ORQ transformation (for instance), the scale of your original unit is not preserved; the only thing that is preserved is the ordering of the observations. However, the reverse ORQ transformation is still possible, so there is still a good option.

My advice would be to check out the package vignette (https://cran.r-project.org/web/packages/bestNormalize/vignettes/bestNormalize.html), specifically the application section, which uses a linear regression on (ORQ) transformed variables. While there is not a (universally) good way to explain mathematically what is happening in this situation, a graphical picture is worth a thousand words; see the last three figures in the vignette for an idea of what I mean. Perhaps you could produce a similar plot for your data and interpret the regression relationship as you see fit? 

While this doesn't give you an interpretation on your specific beta estimates, it gives you a sense of the shape of the relationship between x and y after transformations on the scale of the original unit (the `inverse = TRUE` argument is used on predictions from your model onto new data to yield the graph in the vignette.

Hope this helps, thanks for using my package.
