### ISSUE TITLE
Negative values in Box-Cox transformations

### ISSUE THREAD

**Issue by topepo** [petersonR/bestNormalize#11]
A warning is produces in the devel version of recipes that produces a warning when the BC transformation is used with negative values. 

One of the bestNormalize test cases generates a warning now. 

We'll be sending recipe to CRAN in the next week so FYI...

```
     ERROR
    Running the tests in ‘tests/testthat-methods-step.R’ failed.
    Last 13 lines of output:
      > library(testthat)
      > library(bestNormalize)
      > 
      > test_check(package = 'bestNormalize', filter = "methods|step")
      ══ Skipped tests ═══════════════════════════════════════════════════════════════
      • On CRAN (2)
      
      ══ Failed tests ════════════════════════════════════════════════════════════════
      ── Failure (test_step_fns.R:79:3): step_* transformations with missing/negative/discrete data ──
      `bc_estimates <- prep(bc_trans, training = as.data.frame(iris2))` produced warnings.
      
      [ FAIL 1 | WARN 0 | SKIP 2 | PASS 78 ]
      Error: Test failures
      Execution halted
```

**Comment by petersonR** [comment]
Thank you for the heads up. I think I fixed it in the devel version of `bestNormalize` by checking the `recipes` package version prior to running the test, expecting a warning to be (rightly, I think) thrown when boxcox fails due to negative values. Will close after submitting the devel version to CRAN, hopefully soon.

**Comment by petersonR** [comment]
`bestNormalize` version 1.8.2 off to CRAN, closing this issue.
