### ISSUE TITLE
'No_transform' but different x.t and x

### ISSUE THREAD

**Issue by MelissaRS** [petersonR/bestNormalize#4]
Hi! I have been using the bestNormalize package for data analysis in by bachelorthesis. For one dataset I keep getting the notice "chosen_transform" = "no_transform". However, the provided x.t differs from the original x. How can this be as bestNormalize chose no transformation?

**Comment by petersonR** [comment]
Hi, thanks for pointing this out; I'm guessing the data's being centered and scaled since standardize = TRUE by default. You can fix this by setting standardize = FALSE in the call to bestNormalize. If this solves your problem, please close the issue, thanks. Eventually I may decide to reset the default to standardize = FALSE for this reason, but that will require some thought. I may also take out the option to standardize within no_transform().

**Comment by petersonR** [comment]
I took out the `standardize` option from no_transform in the devel version, so now it should work as expected.

**Comment by markgrujic** [comment]
Hi, thanks for maintaining this package, it is super cool.
I know this is old and closed but thought I'd comment.

What is the consensus on what the expected outcome of a transformation using bestNormalize(standardise=T) where the best transform is no_transform? I feel like x.t should be the centered/scaled data, as that is an explicit argument to the function.

Happy either way, but if you were to loop through several data with the same arguments, you can get significantly different results. Here, I show the distributions of 4 different datasets passed to bestNormalize():
![image](https://user-images.githubusercontent.com/39284163/92062143-5b15d680-eddb-11ea-9066-1910afa7bd88.png)
As you can see above, an extra standardisation function would need to be applied to ensure centred/scaled data.

Cheers

**Comment by markgrujic** [comment]
Further to this, this is my current implementation to get around this issue. Please let me know if you have a better way?
```
bn_data <- bestNormalizeData(x, standardize=T))
# type of transform:
tx_type <- attributes(bn_data$chosen_transform)$class[1]
if(tx_type == "no_transform") bn_data$x.t <- scale(bn_data$x.t)
```

**Comment by petersonR** [comment]
Hmm, this is a good question. I agree that there should be some way of doing this, but I'm not sure the best way to actually implement. The centered/scaled data will have the exact same normalization statistic properties as no_transform, since only an affine transformation is being done. So I can't simply add a `center_scale` transformation option. I feel that adding the `standardize = TRUE` argument back to `no_transform` is incorrect too, since centering and scaling is a transformation, and `no_transform` causes confusion. 

Your fix may cause issues in later calls to `predict` and inverse-ing the transformation. 

Thoughts on changing the name of `no_transform` to either i) `affine_transform`, ii) `center_scale`, or iii)`identity_transform`? I feel like these would cause less confusion if I were to re-introduce the standardize option. At any rate, reopening the issue.

**Comment by markgrujic** [comment]
Hi, yep agree - the current way needs to stay as well. How about if standardize=T, then no_transform becomes center_scale. If standardize=F, then no_transform becomes identity_transform?

**Comment by petersonR** [comment]
Agreed - this is now implemented in the devel version here on GH. I'll update the CRAN version in the next update. Thanks for the suggestion/feedback, and let me know if you run into further issues with this.
